### ISSUE TITLE
Documentation: Mention that the MQTT adapter is an alternate solution for 'advanced' users

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.owntracks#141]
This adapter is useful for 'beginners' but... in reality it is simply starting an MQTT instance, decoding messages and updating specific states as a result.

I think it would be useful to mention in the documentation that if you are already running an instance of the MQTT Adapter and don't mind decoding messages from the OwnTracks topics yourself, then this owntracks adapter is not required.

**Comment by Apollon77** [comment]
Especially the decoding of the messagess and provideing special state is the reason for the adapter. SO I do not think that this is a needed info.

**Comment by raintonr** [comment]
I disagree because when I first found the OwnTracks adapter I thought it was mandatory for integration with OwnTracks apps. It was only after further investigation I figured out that OwnTracks could work with the regular IoB MQTT adapter, thus reducing number of adapters in a system if you already have MQTT runnin.

Or maybe I'm just slow? :clown_face: :wink:

One needs to script something to pass locations from OwnTracks states to Places anyhow (unless I missed something there too) so if using MQTT adapter it's not a big deal to decode yourself like this:

```JavaScript
function ownTracksMQTTToPlaces(mqttStateId) {
    // Pull out username from ID... depending on how the client was configured.
    const idParts = mqttStateId.split('.');
    const user = idParts[idParts.length - 2];

    const owntracksMessage = JSON.parse(getState(mqttStateId).val);

    const placesMsg = {
        user: user,
        latitude: owntracksMessage.lat,
        longitude: owntracksMessage.lon,
        timestamp: owntracksMessage.tst
    };
    sendTo('places', placesMsg);
}
```

None of this is a big deal. It's here in this issue now so someone might stumble across it here :smile:

**Comment by Apollon77** [comment]
Then do a PR with the proposed Readme change if you like ... 

Adapters are especially there to add conveniece for unexperienced users in several such cases ... if we add a disclaimer like "hey you can also do it yourself, just do xyz if you are a profi" that feels wrong ;)

**Comment by raintonr** [comment]
That's OK :wink: 

I guess that if this adapter really is for convenience though, it should integrate into places (when installed) as that would be one less script a new user would need to figure out. But that's not what this issue is actually about.
