### ISSUE TITLE
Object owntracks.0.locations.home.timestamp

### ISSUE THREAD

**Issue by knobi4711** [iobroker-community-adapters/ioBroker.owntracks#20]
"owntracks.0.locations.xxx.timestamp" is too short. 
When converting this date comes: "1970.01.19 01: 46: 29.535". 
If you add 3 zeros to the timestamp, it will work correctly.

**Comment by Zefau** [comment]
Timestamp is 10 digits long (seconds since Jan 01 1970). Adding 3 digits turns it to milli-seconds.

**Comment by Zefau** [comment]
With the new release (see https://github.com/iobroker-community-adapters/ioBroker.owntracks/issues/18) all timestamps and milli-seconds will be converted to date-time as well.
