### ISSUE TITLE
Regions / Locations doesn't works

### ISSUE THREAD

**Issue by stefanoklett** [iobroker-community-adapters/ioBroker.owntracks#21]
Hi,
I just installed the Owntracks (1.0.0-beta.2) with MQTT (2.1.1) and the Regions defined on my android Owntracks apps are not available on the object tree.
I just get the path for the user, with all information and a path Location without with no sub trees.

What I'm forgetting to configure?
Best regards
Stefano

**Comment by Zefau** [comment]
Locations will be available once the payload is received by the adapter. The payload is sent by the apps when the event occurs. Means, when you enter / leave a location / region, the payload is sent by the app and received by the adapter. In that moment the objects are created.

**Comment by stefanoklett** [comment]
Yes, thank,
now I have submitted a new issue

regards
