### ISSUE TITLE
Send cmd to user

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.owntracks#215]

**Comment by mcm1957** [comment]
??? some more info would be fine ???

**Comment by Eistee82** [comment]
https://forum.iobroker.net/topic/43226/mqtt-remote-commands-f%C3%BCr-owntracks-adapter

**Comment by mcm1957** [comment]
Dont know what you want to tell with a link to a three year old discussion commented at a closed issue.

If there is a problem, please open a new issue, describe the problem and add all versions (Adapter, js.controller, admin, node, os) and a debug log.

If you want to request a new feature, please open a new isse and describe the desired extension.
