### ISSUE TITLE
presence in the zone = true, although not in the zone

### ISSUE THREAD

**Issue by stefanoklett** [iobroker-community-adapters/ioBroker.owntracks#25]
Hi,
for unknown reasons, at the exit of the zone the user is removed, leaving a comma in the variable user, this causes the flag presence to be true even if no one is present in the zone.
thnks
Stefano

**Comment by stefanoklett** [comment]
Maybe that's because I'm using nested areas.
In my case I want to be informed if I am approaching or moving away from the central area.

Do you think it can be fixed? Or should I write myself an adapter?

**Comment by Apollon77** [comment]
t about delivering a PR for the project to support it ...
