### ISSUE TITLE
Please add NPM package to iobroker-community-adapters:developers team

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.owntracks#27]
verifying all repos and NPM ownership we noticed the NPM package of this repo is not part of our team.

please execute : 

`npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>`

or add the package by web : 

https://www.npmjs.com/settings/iobroker-community-adapters/teams/team/developers/access

**Comment by Zefau** [comment]
@Apollon77 Could you do that? I'm currently working on finalizing v1.0.0 of this adapter and would like to push it to npm at a certain time. Thanks in advanced!

**Comment by Apollon77** [comment]
You need to do that because you own the npm repo

**Comment by Zefau** [comment]
ioBroker community has no access on npm so far.
Current collaborators are: @AlCalzone @Apollon77 bluefox, iobluefox  and ldittmar.

![image](https://user-images.githubusercontent.com/14368811/68995050-da0c4380-0889-11ea-9fbe-b1d741af54cb.png)

**Comment by Apollon77** [comment]
Aahhhh ok ;-)

**Comment by Apollon77** [comment]
done
