### ISSUE TITLE
v1.0.0-rc.1 lässt sich nicht installieren // npm ERR! code E404

### ISSUE THREAD

**Issue by Paul8119** [iobroker-community-adapters/ioBroker.owntracks#32]
Hallo zusammen,

wegen der CloudMqtt Anbindung wollte ich mir die rc.1 installieren. Leider scheint der Fork fehlerhaft zu sein. Könnte das jemand überprüfen?

Danke
Gruß
Paul

$ ./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.owntracks/tree/v1.0.0-rc.1"
install https://github.com/iobroker-community-adapters/ioBroker.owntracks/tree/v1.0.0-rc.1/tarball/b169c3f2003431d7db8233784df9c3e9f6a10773
NPM version: 6.13.4
npm install https://github.com/iobroker-community-adapters/ioBroker.owntracks/tree/v1.0.0-rc.1/tarball/b169c3f2003431d7db8233784df9c3e9f6a10773 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code E404
npm
 ERR! 
404
 Not Found - GET https://github.com/iobroker-community-adapters/ioBroker.owntracks/tree/v1.0.0-rc.1/tarball/b169c3f2003431d7db8233784df9c3e9f6a10773npm 
ERR! 404 npm ERR! 404  'https://github.com/iobroker-community-adapters/ioBroker.owntracks/tree/v1.0.0-rc.1/tarball/b169c3f2003431d7db8233784df9c3e9f6a10773' is not in the npm registry.
npm ERR!
 
404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR!
 
404 npm ERR!
 404 Note that you can also install from anpm ERR! 404
 tarball, folder, http url, or git url.

npm 
ERR! A complete log of this run can be found in:
npm
 ERR!     /home/iobroker/.npm/_logs/2020-02-11T06_00_01_376Z-debug.log
upload [17] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/words.js words.js application/javascript
…

**Comment by Zefau** [comment]
```
iobroker url https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/v1.0.0-rc.1  
```

**Comment by Paul8119** [comment]
DANKE!
