### ISSUE TITLE
Adapter isn't working in iobroker@docker

### ISSUE THREAD

**Issue by FreAcX** [iobroker-community-adapters/ioBroker.owntracks#36]
Tested your adapter yesterday evening and can't it get to work. Maybe it's a iobroker@docker-issue? MQTT-Broker runs on another adapter.
Errors from log:

host.iobroker_2 | 2020-05-22 08:19:50.527 | error | Caught by controller[0]: }
-- | -- | -- | --
host.iobroker_2 | 2020-05-22 08:19:50.527 | error | Caught by controller[0]: port: 1883
host.iobroker_2 | 2020-05-22 08:19:50.527 | error | Caught by controller[0]: address: '0.0.0.0',
host.iobroker_2 | 2020-05-22 08:19:50.527 | error | Caught by controller[0]: syscall: 'listen',
host.iobroker_2 | 2020-05-22 08:19:50.527 | error | Caught by controller[0]: errno: 'EADDRINUSE',
host.iobroker_2 | 2020-05-22 08:19:50.526 | error | Caught by controller[0]: code: 'EADDRINUSE',
host.iobroker_2 | 2020-05-22 08:19:50.526 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:85:21) {
host.iobroker_2 | 2020-05-22 08:19:50.526 | error | Caught by controller[0]: at doListen (net.js:1500:7)
host.iobroker_2 | 2020-05-22 08:19:50.526 | error | Caught by controller[0]: at listenInCluster (net.js:1361:12)
host.iobroker_2 | 2020-05-22 08:19:50.526 | error | Caught by controller[0]: at Server.setupListenHandle [as _listen2] (net.js:1313:16)
host.iobroker_2 | 2020-05-22 08:19:50.525 | error | Caught by controller[0]: Error: listen EADDRINUSE: address already in use 0.0.0.0:1883

The IP is everytime 0.0.0.0, no matter what I choose in the configuration of the adapter.

**Comment by Apollon77** [comment]
The error means that some othe rprocess uses the port 1883 which is also needed by this adapter. Fix that and the adapter will run

**Comment by FreAcX** [comment]
Hey Ingo,
so the Adapter can't run when I've a MQTT-Broker running on Port 1883? So
I've to use a online Broker or a second device, where my broker runs?

Greetings


Ingo Fischer <notifications@github.com> schrieb am Fr., 22. Mai 2020, 23:53:

**Comment by Apollon77** [comment]
In der Owntracks Adapter Konfig kann der Port eingestellt werden ... aber ja owntracks nutzt einen eigenen MQTT Server ...
