### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by schweigel** [iobroker-community-adapters/ioBroker.owntracks#50]
Hello,

in my log, I found the following errors:
![image](https://user-images.githubusercontent.com/52450003/97103765-d5155e00-16ae-11eb-847c-2865a713ce77.png)

I use the latest version of owntracks: 0.6.3

On my mobile devices sometimes I get an MQTT error.

Thank you.

**Comment by Apollon77** [comment]
The error happens when somehow the password of the package is not set

**Comment by schweigel** [comment]
Ok, what can I do to prevent this error?

**Comment by Apollon77** [comment]
I could catch it but honestly I have no idea what will be the effect then - because I do not use this. So would be a blind change ...

**Comment by Apollon77** [comment]
Please check Github version
