### ISSUE TITLE
IPv6 blocked on set owntracks port

### ISSUE THREAD

**Issue by Leo445566** [iobroker-community-adapters/ioBroker.owntracks#53]
Hi Team,

today I detect an issue in version 0.6.3 by using IPv6.

In the settings (see below) I select IPv6 but my raspi only open the selected port 1883 for ipv4 addresses.
![2020-11-27_122519](https://user-images.githubusercontent.com/75122854/100444385-a6264980-30ab-11eb-9d73-0ab6ea9d296b.jpg)

With the netstat call "sudo netstat -lnptu -A inet", I see port 1883 is open for ipv4.
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      13234/io.owntracks.

But with the call "sudo netstat -lnptu -A inet6", the port is not open for IPv6. Therefore, my raspi block these port.
Same happen in case I change the port to (for example 8883). 

Is there a workaround? Currently it's only working internally at home, which makes no sense for a tracker application. 

Many thans in advance,
Leo

**Comment by Apollon77** [comment]
Hm ... short code check shows that the "Bind IP" you select there is not used at all at the moment ... and this is then the reason.

**Comment by Leo445566** [comment]
Thanks Apollon, 
I'm looking forward to get this realized as IPv6 will be the standard, if not so far already.
Ploblem is, that home network (where the server is located) is only accessable via ipv6 from external.

**Comment by Apollon77** [comment]
Please check Github version

**Comment by Leo445566** [comment]
Hi Apollon,

Many thanks. I removed the current and installed the new version from the Github. 
It ends with exit code 0 but there are several errors during the installation. Please see below the full list.

$ ./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/master" owntracks
install https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/master
NPM version: 6.13.6
npm install https://github.com/iobroker-community-adapters/ioBroker.owntracks/tarball/master --loglevel error --prefix "/opt/iobroker" (System call)
Package pangocairo was not found in the pkg-config search path.Perhaps you should add the directory containing `pangocairo.pc'to the PKG_CONFIG_PATH environment variableNo package 'pangocairo' foundgyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp
 ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.72-v7l+gyp
 ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.0.5gyp ERR! not ok 
node-pre-gyp 
ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp ERR!
 stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)node-pre-gyp ERR! System Linux 5.4.72-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v10.21.0node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
upload [17] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/words.js words.js application/javascript
upload [16] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/owntracks.png owntracks.png image/png
upload [15] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/index_m.html index_m.html text/html
upload [14] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/index.html index.html text/html
upload [13] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/image.editor.js image.editor.js application/javascript
upload [12] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/image.editor.css image.editor.css text/css
upload [11] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [10] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [9] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [8] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [7] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [6] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [5] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [4] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [3] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [2] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [1] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/admin.js admin.js application/javascript
upload [0] owntracks.admin /opt/iobroker/node_modules/iobroker.owntracks/admin/admin.css admin.css text/css
process exited with code 0

**Comment by Apollon77** [comment]
These are only warnings originationnfrom other adapters, maybe iot or other that uses canvas and pangocairo ... so irelevantfor this

**Comment by Leo445566** [comment]
Ah, okay ... sound good.
However, the overtracks is not shown in the instance list 

![grafik](https://user-images.githubusercontent.com/75122854/100617964-7bdac300-331b-11eb-82c5-33f4b220f30c.png)

**Comment by Apollon77** [comment]
installs via github do not create a instance ... click the "+" on "Adapter" tab for the adapter :-)

**Comment by Leo445566** [comment]
Indeed, thanks for this. 
Owntracks installed and is now present in the instance list 👍 .

Now I choose the settings below and add route portforwarding to the raspi on port 1883 for ipv6
![grafik](https://user-images.githubusercontent.com/75122854/100664641-37b9e380-3358-11eb-8b70-98fea7ad5e59.png)

When I now asked the raspi for open ipv6 ports via "sudo netstat -lnptu -A inet6", the port is still not open :-( .
Is there anything else I did wrong?

**Comment by Apollon77** [comment]
Please go to objects and empty all filters and search for "system.adapter.owntracks.0" and click in that link right ión the pencil icon. Then go to the Raw tab and provide the json you see there here, especially native-> bind. whats the value?

**Comment by Leo445566** [comment]
Good morning Apollon,
Thanks ... please find below the content of the RAW tab.

The native part is following:
 "native": {
    "port": "1883",
    "user": "iobroker",
    "pass": ".\u000e\u0012\u0013[_\u0004u",
    "secure": false,
    "pictures": [],
    "bind": "::",
    "certPublic": "defaultPublic",
    "certPrivate": "defaultPrivate",
    "certChained": "",
    "leEnabled": false,
    "leUpdate": false,
    "leCheckPort": 80,
    "encryptionKey": "",
    "webSocket": false
  },

Please find below the full content.
{
  "common": {
    "name": "owntracks",
    "version": "0.6.3",
    "title": "OwnTracks - Your location companion",
    "desc": {
      "en": "OwnTracks allows you to keep track of your own location in ioBroker",
      "de": "Mit OwnTracks können Sie Ihren eigenen Standort in ioBroker verfolgen",
      "ru": "OwnTracks позволяет отслеживать ваше собственное местоположение в ioBroker",
      "pt": "OwnTracks permite que você acompanhe sua própria localização no ioBroker",
      "nl": "Met OwnTracks kunt u uw eigen locatie in ioBroker bijhouden",
      "fr": "OwnTracks vous permet de garder une trace de votre propre emplacement dans ioBroker",
      "it": "OwnTracks ti consente di tenere traccia della tua posizione in ioBroker",
      "es": "OwnTracks le permite realizar un seguimiento de su propia ubicación en ioBroker",
      "pl": "OwnTracks pozwala na śledzenie własnej lokalizacji w ioBroker",
      "zh-cn": "OwnTracks允许您在ioBroker中跟踪自己的位置"
    },
    "news": {
      "0.6.3": {
        "en": "some issues are fixed and dependencies updated",
        "de": "Einige Probleme wurden behoben und Abhängigkeiten aktualisiert",
        "ru": "исправлены некоторые проблемы и обновлены зависимости",
        "pt": "alguns problemas são corrigidos e as dependências atualizadas",
        "nl": "sommige problemen zijn opgelost en afhankelijkheden zijn bijgewerkt",
        "fr": "certains problèmes sont corrigés et les dépendances mises à jour",
        "it": "alcuni problemi sono stati risolti e le dipendenze aggiornate",
        "es": "algunos problemas son corregidos y las dependencias actualizadas",
        "pl": "niektóre problemy zostały naprawione, a zależności zaktualizowane",
        "zh-cn": "一些问题已修复，相关性已更新"
      },
      "0.6.2": {
        "en": "Added Compact mode and Gulp translations",
        "de": "Kompakter Modus und Gulp-Übersetzungen hinzugefügt",
        "ru": "Добавлены компактный режим и перевод Gulp",
        "pt": "Adicionado modo Compact e traduções Gulp",
        "nl": "Compact-modus en Gulp-vertalingen toegevoegd",
        "fr": "Ajout des traductions en mode Compact et Gulp",
        "it": "Aggiunte le modalità Compact e Gulp",
        "es": "Agregado el modo compacto y Gulp traducciones",
        "pl": "Dodano tryb kompaktowy i tłumaczenia Gulp",
        "zh-cn": "增加了紧凑模式和Gulp翻译"
      },
      "0.6.0": {
        "en": "Added Admin v3 / materialized support",
        "de": "Admin v3 support"
      },
      "0.5.1": {
        "en": "Fixed an error when connection got closed",
        "de": "Fehler beseitigt, wenn die Verbindung geschlossen wird"
      },
      "0.5.0": {
        "en": "Added support for defined locations",
        "de": "Unterstützung für Regionen hinzugefügt"
      },
      "0.4.0": {
        "en": "Added support for encryption key (on Android see Preferences -> Advanced -> Encryption Key)",
        "de": "Unterstützung zur Verschlüsselung hinzugefügt (auf Android unter Preferences -> Advanced -> Encryption Key)"
      },
      "0.3.0": {
        "en": "Fix handling of publish messages",
        "de": "Problem in der Abarbeitung von publish-Nachrichten behoben"
      },
      "0.2.0": {
        "en": "added two properties timestamp and datetime",
        "de": "Timestamp und datetime sind hinzugefügt",
        "ru": "Добавлены время последнего сообщения в разных форматах"
      },
      "0.1.1": {
        "en": "add pictures",
        "de": "Unterstützung von Bildern",
        "ru": "Возможность добавить иконки"
      },
      "0.1.0": {
        "en": "initial checkin",
        "de": "Erste version",
        "ru": "первая версия"
      }
    },
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "icon": "owntracks.png",
    "extIcon": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.owntracks/master/admin/owntracks.png",
    "keywords": [
      "owntracks",
      "position",
      "gps",
      "geo"
    ],
    "readme": "https://github.com/iobroker-community-adapters/ioBroker.owntracks/blob/master/README.md",
    "loglevel": "info",
    "type": "geoposition",
    "materialize": true,
    "compact": true,
    "authors": [
      {
        "name": "bluefox",
        "email": "dogafox@gmail.com"
      },
      {
        "name": "Zefau",
        "email": "zefau@mailbox.org"
      }
    ],
    "dependencies": [
      {
        "js-controller": ">=2.0.0"
      }
    ],
    "installedFrom": "https://github.com/iobroker-community-adapters/ioBroker.owntracks#iobrokerowntracks/tarball/master",
    "installedVersion": "0.6.3",
    "enabled": true,
    "host": "raspi41"
  },
  "native": {
    "port": "1883",
    "user": "iobroker",
    "pass": ".\u000e\u0012\u0013[_\u0004u",
    "secure": false,
    "pictures": [],
    "bind": "::",
    "certPublic": "defaultPublic",
    "certPrivate": "defaultPrivate",
    "certChained": "",
    "leEnabled": false,
    "leUpdate": false,
    "leCheckPort": 80,
    "encryptionKey": "",
    "webSocket": false
  },
  "type": "instance",
  "from": "system.host.raspi41.cli",
  "ts": 1606770926966,
  "_id": "system.adapter.owntracks.0",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

**Comment by Apollon77** [comment]
I have found something ... https://github.com/node-red/node-red/issues/2462

Please edit the object from above (so open that "raw tab again") and then edit that one line too

 "bind": "[::]",

is it working then?

**Comment by Leo445566** [comment]
Hi Apollon,
Many thanks for investigating. Yeah, that was it !!! 
IPv6 needs the brackets [ ]. 

Many thanks again, I really appreciate it !!!

**Comment by Apollon77** [comment]
I now just need to think about on how to make that generic ... hm ...

**Comment by Leo445566** [comment]
Hi Apollon,
right. Please let me know if I can support you, testing or anything else you have in mind.

**Comment by Apollon77** [comment]
Ok, then we try to fix it right :-)
Please revert the chaange in the config (or go to admin and save settings again - this should override that again). Then install github version. Does it still work?
The "bind" parameter is now checked and if it is ipv6 then the brackets are added

**Comment by Apollon77** [comment]
@Leo445566 Did you had a chance?

**Comment by Leo445566** [comment]
Hi Apollon,
Sorry, I was offline yesterday but could test it right now.
Yes, I can confir that it's working with the new version from gitbub. In the system.adapter.owntracks setting (RAW) I have following content (see below) ... but it works perfect for ipv6 vom internal WLAN or external via mobile data :-) 

"native": {
    "port": 1883,
    "user": "iobroker",
    "pass": "",
    "secure": false,
    "pictures": [],
    "bind": "0.0.0.0",
    "certPublic": "defaultPublic",
    "certPrivate": "defaultPrivate",
    "certChained": "",
    "leEnabled": false,
    "leUpdate": false,
    "leCheckPort": 80
  },

Great work !!!

**Comment by Apollon77** [comment]
cool, then I publish this to npm soon. Thank you for your support
