### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Jaaannis** [iobroker-community-adapters/ioBroker.owntracks#57]
**Describe the bug**  
Hi,

i became an error regulary, it is called :  (1516) [user] Error: read ECONNRESET
followed immediatly by: (1516) Client [user] closed
Can anyone explain what it is?
Thank you 

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 3.1.6
 - Node version: <node-version> v12.20.0
 - Operating system: Raspios

**Comment by Apollon77** [comment]
ECONNRESET means that the network partner youconnect to unexpectedly closes the connection
