### ISSUE TITLE
Cannot parse payload

### ISSUE THREAD

**Issue by df1gr** [iobroker-community-adapters/ioBroker.owntracks#6]
Hi,
get the error message from own tracks from the try block within client.on('subscribe', function (packet) 
in main.js. Using latest released own tracks adapter 0.2.0.
I assume that the reason for the fault is the following JSON data line: 
{"cog":136,"batt":75,"lon":9.227956132971894,"acc":10,"vel":0,"vac":4,"lat":47.72337962412063,"t":"u","conn":"m","tst":1494851972,"alt":394,"_type":"location","tid
The last key tid is not correctly terminated as any other records coming from iPhone App. I'm using OwnTracks version 9.3.0/de_DE on my iPhone. 

I assume that any buffer might be to short to receive the "cog" data.

Any help or fix would be appreciated.
Thank you in advance.

df1gr

**Comment by df1gr** [comment]
Clarification: the error message comes from iobroker.owntracks. I checked this with the own track project itself and get the following answer:
This is most likely an iobroker issue then; we are not aware of any iOS app versions which truncate outgoing data (nothing at all would work if that happened). If I were you I'd ask the other project.
df1gr

**Comment by GermanBluefox** [comment]
Why you closed that?

19 Май 2017 г. 10:11 пользователь "df1gr" <notifications@github.com>
написал:

**Comment by df1gr** [comment]
Hi,

sorry, used the wrong button by mistake. Can I reopen the issue again?
I’m a newbie in GitHub!

df1gr

**Comment by GermanBluefox** [comment]
Yes. You can reopen it

19 Май 2017 г. 10:23 пользователь "df1gr" <notifications@github.com>
написал:

**Comment by df1gr** [comment]
Thanks,
done!

df1gr

**Comment by df1gr** [comment]
Hi,
is any diagnostic of the problem available?

**Comment by df1gr** [comment]
Dear Zefau,

No, I didn’t get the error again so far.
.
So, thank you for asking.

Regards,
Roland

**Comment by Zefau** [comment]
@Apollon77 can be closed, thanks
