### ISSUE TITLE
Datenpunkt lässt sich nicht anpassen 

### ISSUE THREAD

**Issue by ipod86** [iobroker-community-adapters/ioBroker.owntracks#80]
Hallo, 

ich wollte eben beim Adapter für manche Datenpunkte Raum und Funktion einstellen. Leider darf ich die Datenpunkte nicht alle bearbeiten. 

Im speziellen betrifft es die Zeile location. In der Zeile location und david gibt es auch keinen Schreibenschlüssel.

Darf das beides so sein?

![Screenshot_20210715-151624_Firefox~2](https://user-images.githubusercontent.com/66136363/125976368-72e8bdb1-1d9c-4847-a376-8b91c038956c.jpg)

**Comment by Apollon77** [comment]
Sieht so aus als ob das Objekt nicht angelegt wäre. Das müsste dann gefixt werden
