### ISSUE TITLE
Falsche Rolle vergeben? 

### ISSUE THREAD

**Issue by ipod86** [iobroker-community-adapters/ioBroker.owntracks#81]
Hallo, 

die GPS Koordinaten sind in den Rollen mit gps.latitude und gps.longitude vergeben. 

@Garfonso hat mich eben drauf hingewiesen, dass es value.gps.xxxxx sein müsste.

![Screenshot_20210715-151624_Firefox~2](https://user-images.githubusercontent.com/66136363/125976867-3978ab9e-ea0d-4f88-b02e-c219eb7a16a8.jpg)

**Comment by Garfonso** [comment]
This still seems to be the case... I created a pull request to solve this issue...
https://github.com/iobroker-community-adapters/ioBroker.owntracks/pull/92

Currently I don't know, when I find the time to test this.. so if anybody else can test we could merge faster, maybe.

(to test you can install from git URL: `iobroker-community-adapters/ioBroker.owntracks#Garfonso-patch-1`  - also you'd need to delete all existing objects / create a new user)

**Comment by Garfonso** [comment]
Issue is still there.

**Comment by Apollon77** [comment]
fixed in next update
